name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_HYPERION }}
        run: |
          npx vercel@latest deploy --prod --token "$VERCEL_TOKEN" --yes
